### ISSUE TITLE
Site makes two different claims

### ISSUE THREAD

**Issue by tsal** [fosstodon/hub#10]
![image](https://github.com/fosstodon/hub/assets/1747304/81d59fa2-0323-4f40-9b06-5b05115bf8ee)
![image](https://github.com/fosstodon/hub/assets/1747304/19eea918-dc56-4cb1-a432-43ae09c6bb75)

**Comment by tsal** [comment]
not to mention how terrible this looks that you gave zero notice on this, and that action (or lack thereof) is contradictory to the community you seem to want to build, based on that blog post. I get the reasoning, I do, but damn, guys. woulda been nice to know this was coming _while I was literally figuring out what Mastodon instance I wanted to use_. 

You'll probably think this is being "overly sensitive" or just "toxic complaining", but realize that closing the garden gates while people are still looking to come in is pretty dang toxin-inducing.

**Comment by kevquirk** [comment]
We made a decision for the benefit of our extremely over-worked moderation team, and to encourage decentralisation, as people will inevitably join other servers, instead of ours.

There's plenty of great instances you could join. But if you specifically wanted to join Fosstodon, you could have emailed the team requesting an invite link instead of complaining. 🤷‍♂️

**Comment by tsal** [comment]
> We made a decision for the benefit of our extremely over-worked moderation team, and to encourage decentralisation, as people will inevitably join other servers, instead of ours.

 I get that, I really do, but this:
 
 > But if you specifically wanted to join Fosstodon, you could have emailed the team requesting an invite link instead of complaining.
 
 You kind of went out of your way in the blog post to imply that "if you don't know someone, too bad" -- just without actually saying it.
 
 I'm not so much complaining about the decision, I'm complaining about how it was delivered, in a vacuum, with "Open" in the dang acronym.
 
 nice touch closing the issue without discussion.
