### ISSUE TITLE
Fosstodon is down for 2 days now?

### ISSUE THREAD

**Issue by FairyPenguin** [fosstodon/hub#9]
Evening 

hope everything is Okay 

but Fosstodon is not working for me for 2 days now 

I tried different browsers, apps, and clear caching but not working 
But in the server status, it's working fine! 

is this only me or is Fosstodon down?

![image](https://github.com/fosstodon/hub/assets/37639473/4f4be753-c471-48d9-bcac-3dd26b0b573d)

**Comment by kevquirk** [comment]
It's you I'm afraid. Fosstodon hasn't had any outages.
